name: deploy

on:
  push:
    branches:
    - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: bundler install, npm install, test
      run: |
        gem install bundler jekyll
        bundle install --jobs 4 --retry 3&npm ci
        npm test
      env:
        CI: true

    - name: build
      run: |
        npm run build --if-present
      env:
        CI: true
      
    - name: deploy
      run: |
        git init
        git config user.name "Ebagcoder"
        git config user.email "Ebagcoder@users.noreply.github.com"
        git add .
        git commit -m 'Deploy to GitHub Pages'
        git push --force "https://$GH_PAT@github.com/$GITHUB_REPOSITORY.git" master:master
        rm -fr .git
      working-directory: ./dist
      env:
        CI: true
        GH_PAT: ${{ secrets.GH_PAT }}
